
// import { createClient } from '@supabase/supabase-js';

// ===================================================================
// INTEGRASI SUPABASE DINONAKTIFKAN
// Aplikasi ini sekarang menggunakan data dummy.
// Untuk mengaktifkan kembali, hapus komentar pada kode di bawah ini
// dan pastikan file .env Anda sudah dikonfigurasi.
// ===================================================================

/*
const supabaseUrl = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

if (supabaseUrl === 'YOUR_SUPABASE_URL' || supabaseAnonKey === 'YOUR_SUPABASE_ANON_KEY') {
    // Error ini akan ditangkap oleh ErrorBoundary kita.
    // Ini mencegah Supabase client crash dengan error yang kurang spesifik.
    throw new Error('Supabase URL/Key is not configured. Please add your credentials in services/supabase.ts');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
*/

/**
 * SQL for table setup:
 *
 * -- Create daily_checklist_logs table
 * CREATE TABLE public.daily_checklist_logs (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
 *   log_date DATE NOT NULL,
 *   completed_items INTEGER[] DEFAULT '{}'::INTEGER[],
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
 *   CONSTRAINT unique_user_date UNIQUE (user_id, log_date)
 * );
 *
 * -- Enable Row Level Security (RLS)
 * ALTER TABLE public.daily_checklist_logs ENABLE ROW LEVEL SECURITY;
 *
 * -- Policies for RLS
 * CREATE POLICY "Users can view their own logs."
 * ON public.daily_checklist_logs
 * FOR SELECT USING (auth.uid() = user_id);
 *
 * CREATE POLICY "Users can insert their own logs."
 * ON public.daily_checklist_logs
 * FOR INSERT WITH CHECK (auth.uid() = user_id);
 *
 * CREATE POLICY "Users can update their own logs."
 * ON public.daily_checklist_logs
 * FOR UPDATE USING (auth.uid() = user_id);
 *
 */
