
import { createClient } from '@supabase/supabase-js';

// ===================================================================
// KONFIGURASI SUPABASE
// ===================================================================
// Masukkan URL dan ANON KEY dari dashboard Supabase Anda di sini.
// Caranya: Project Settings -> API
// ===================================================================

// 1. Ganti string kosong di bawah ini dengan Project URL Anda
const SUPABASE_URL = 'https://hphigcpyvwveipbetxiy.supabase.co'; 

// 2. Ganti string kosong di bawah ini dengan Anon Public Key Anda
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaGlnY3B5dnd2ZWlwYmV0eGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNjM2OTUsImV4cCI6MjA4MDczOTY5NX0.yaTEVcDblG-bizFv8sdV0KCMbrbiENq1fOu6snpwpaU';

// ===================================================================

const supabaseUrl = process.env.SUPABASE_URL || SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    // Error ini akan ditangkap oleh ErrorBoundary jika Anda lupa mengisi key di atas.
    throw new Error('Supabase URL/Key is not configured. Please add your credentials in services/supabase.ts');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * ==================================================================================
 * SQL SETUP SCRIPT
 * Salin dan Jalankan semua kode di bawah ini di "SQL Editor" Supabase Anda:
 * ==================================================================================
 
-- 1. Buat Tabel 'checklist_tasks' (Menyimpan daftar tugas)
create table if not exists public.checklist_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Aktifkan keamanan (RLS) untuk checklist_tasks
alter table public.checklist_tasks enable row level security;

-- Kebijakan (Policies) untuk checklist_tasks
create policy "Users can view their own tasks" on public.checklist_tasks for select using (auth.uid() = user_id);
create policy "Users can insert their own tasks" on public.checklist_tasks for insert with check (auth.uid() = user_id);
create policy "Users can update their own tasks" on public.checklist_tasks for update using (auth.uid() = user_id);
create policy "Users can delete their own tasks" on public.checklist_tasks for delete using (auth.uid() = user_id);


-- 2. Buat Tabel 'daily_checklist_logs' (Menyimpan riwayat checklist harian)
create table if not exists public.daily_checklist_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  log_date date not null,
  completed_items integer[] default array[]::integer[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_user_date unique(user_id, log_date)
);

-- Aktifkan keamanan (RLS) untuk daily_checklist_logs
alter table public.daily_checklist_logs enable row level security;

-- Kebijakan untuk daily_checklist_logs
create policy "Users can view their own logs" on public.daily_checklist_logs for select using (auth.uid() = user_id);
create policy "Users can insert their own logs" on public.daily_checklist_logs for insert with check (auth.uid() = user_id);
create policy "Users can update their own logs" on public.daily_checklist_logs for update using (auth.uid() = user_id);

-- 3. Buat Tabel 'profiles' (Menyimpan data pengguna)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  avatar_id text default 'cow-1',
  notification_enabled boolean default false,
  notification_time time default '08:00:00',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tambahkan kolom untuk sistem progresi (jalankan JIKA tabel sudah ada sebelumnya)
-- Jika ini adalah setup baru, kolom-kolom ini sebaiknya ada di 'create table'
alter table public.profiles add column if not exists level integer default 1 not null;
alter table public.profiles add column if not exists xp integer default 0 not null;
alter table public.profiles add column if not exists current_streak integer default 0 not null;
alter table public.profiles add column if not exists longest_streak integer default 0 not null;
alter table public.profiles add column if not exists last_completed_date date;


-- Aktifkan keamanan (RLS) untuk profiles
alter table public.profiles enable row level security;

-- Kebijakan untuk profiles
create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);

 */
